FROM ubuntu:16.04
MAINTAINER Tomas Jacik <tomas@jacik.cz>

ADD image /build

RUN /build/prepare.sh && \
	/build/system_services.sh && \
	/build/packages.sh 7.0 && \
	/build/cleanup.sh

CMD ["/sbin/my_init"]
